### ISSUE TITLE
README: AllowOverride not allowed in <VirtualHost> context

### ISSUE THREAD

**Issue by peterus** [qvarforth/trackdirect#1]
Apache is giving this error when I am following the readme:

`AllowOverride not allowed in <VirtualHost> context`

**Comment by peterus** [comment]
this looks like working:

<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot /home/USER/trackdirect/htdocs/public

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<Directory "/home/USER/trackdirect/htdocs/public">
	Options Indexes MultiViews
	AllowOverride None
	Require all granted
</Directory>

**Comment by qvarforth** [comment]
Thank you for pointing that out. It's fixed now.
