### ISSUE TITLE
Show own symbol for paragliders

### ISSUE THREAD

**Issue by FlyingBird22** [qvarforth/trackdirect#10]
**Show own symbol for paragliders**
In OGN database there are **9%** paragliders and **0.6%** hanggliders registered.
They both are still sharing the same symbol (hangglider).
The number of registered paragliders will increase.
It is time to give paragliders an own symbol.

![image](https://user-images.githubusercontent.com/69727555/154324285-c6025320-4e50-4be6-9121-7bbdc8693f3f.png)

![Paraglider](https://user-images.githubusercontent.com/69727555/154327723-a209e860-85ec-48a3-b76c-4ba3629101f2.PNG)

**Comment by qvarforth** [comment]
After the last fix we now have a solution for this issue. Closing it.
