### ISSUE TITLE
Update TrackDirect 

### ISSUE THREAD

**Issue by T-Shilov** [qvarforth/trackdirect#15]
Hello, Per,

I have installed the initial version of your  TrackDirect  program.
It works great!

Now I want to update his but I didn't find instructions on how to do it.

Could you provide us a Bash-script to update TrackDirect?  

PS. Without installing docker, I don't need it.

**Comment by qvarforth** [comment]
Hi,

What do you mean by "update"? If you want the latest changes from the repository you do a git pull.

**Comment by T-Shilov** [comment]
Hi,

Thank you very much!  Will docker be added too?

**Comment by qvarforth** [comment]
Yes, @peterus has added docker support. If you fetch the latest version you should be able to use docker.

**Comment by T-Shilov** [comment]
Ok, what if I don't need a docker? Will he interfere with the work TrackDirect?

**Comment by qvarforth** [comment]
If you don't want to use docker you just don't use it.

**Comment by peterus** [comment]
lets bring some light into this discussion ☺️
you can install trackdirect directly on your machine with the commands in the readme.
as there where no database updates, you just download (or `git pull`) the new code and restart your services.
thats it!

if you want to use docker, you just need to install the docker engine and a helper tool which is called docker-compose. you do not need to install all the other dependencies for trackdirect.
than you build the docker images by your own (`docker-compose.yml`) or use the docker images which are automatically build by docker hub (`docker-compose-rel.yml`).

the nice thing about using docker: if you want to install trackdirect on a new server you need like 10 min to have it up and running. most part is for setting up the configuration.
if you want to update to the latest version you just beed 2 commands:
```
docker-compose pull
docker-compose up -d
```

**Comment by T-Shilov** [comment]
Thank you, **peterus**

TrackDirect has already been installed in the usual way and is working successfully, so docker is superfluous here.
And I don't want to reinstall everything again, let it stay as it is.

**Comment by peterus** [comment]
in the end you just need to update the code in your home folder. no other updates are necessary except the configuration file.

**Comment by FlyingBird22** [comment]
Hi folks,

great you also setup TrackDirect on own server. This is a work still in front of me.
Is there a web addresss to try out your server?
If for test only, I would be glad, if you could write a pm mailto:David.Maerz@gmx.de

Dave

**Comment by T-Shilov** [comment]
Hi,

`If you want the latest changes from the repository you do a git pull.`

This is a bad instruction. It doesn't work:

`~/trackdirect$ git pull https://github.com/qvarforth/trackdirect
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/qvarforth/trackdirect
 * branch            HEAD       -> FETCH_HEAD
Updating bf7146f..026b15f
error: Your local changes to the following files would be overwritten by merge:
        config/trackdirect.ini
        htdocs/public/about.php
        htdocs/public/index.php
Please commit your changes or stash them before you merge.
Aborting
`

**Comment by qvarforth** [comment]
Hi,

I'm sorry but creating an "issue" is supposed to be about a problem in the actual code, not about needing git support, that why I only gave you a short answer. 

You need to first stash your current changes (git stash), then do a pull (git pull) and at last do a stash pop (git stash pop). You will probably end up with some merge collisions that you need to solve.

There are several good git tutorials online, search and you will find.

I will close this issue now. If you find a problem in the code (or suggestion on how to improve something) you are very welcome to create a new issue.

Best Regards,
Per

FlyingBird22: Multiple links to different servers can be found on aprsdirect.com (you can for example look at my own server gliderradar.com)
