### ISSUE TITLE
Severe memory leak detected

### ISSUE THREAD

**Issue by T-Shilov** [qvarforth/trackdirect#18]
Hi Per,

Unfortunately, in the process of using TrackDirect, a serious memory leak was discovered.
RAM or swap partition for **6-7** days overflows every time and the system collapses.
I've tried different combinations of swap partition volume and **swappiness** ratio **0** to **60**, but it doesn't help.
So far, I have temporarily switched to a daily reboot of the system, but this is not the best solution.

Per, I very hope you will solve this annoying problem.

![memory-leak](https://user-images.githubusercontent.com/61428202/156944912-2124945e-1724-445b-b36f-66c94b8a9665.png)

**Comment by qvarforth** [comment]
I have been running this code for several years and have never seen this problem (one of my current servers has been up for 64 days).

Do you have the possibility to add information about which process that eats all the memory? (current data applies to the entire virtual server which means it could be anything)

**Comment by T-Shilov** [comment]
Hello Per,

I installed the **smem** utility this morning and am monitoring the memory behavior.
It's too early to say for sure, but we can assume that this process is to blame:

python2 ./bin/collector.py the track is straight.mini 0

Because in the morning he "ate" 300 MB:

2022.04.05 10:20:01
```
----------------------------------------------------------
PID User     Command      Swap      USS      PSS      RSS
835 aprs map  python2 ./bin/collector.py   0 314.9M   315.2M   320.8M
```

and in 2022.04.05 19:25:01 it became more:
```
----------------------------------------------------------
PID User     Command    Swap      USS      PSS      RSS
 835 aprs map  python2 ./bin/collector.py  0  464.1M   464.4M   470.0M
```

And it continues to grow further.

I will continue to observe and inform you about the behavior of this process.

**Comment by T-Shilov** [comment]
Hi,

April, 6
It became even more: 1013.2 MB

![April 6](https://user-images.githubusercontent.com/61428202/162024523-492544e1-2be6-40d1-82ba-ea136a9f7cb0.jpg)

**Comment by T-Shilov** [comment]
Hi,

Continue:

**![April 8](https://user-images.githubusercontent.com/61428202/162486000-040b3faa-449e-46e5-8744-00e024aaed2d.png)**

**Comment by qvarforth** [comment]
The collector has a lot in memory to handle the frequency limit (to avoid having to always fetch to much from db). The intention was never for this data to be this large. I will try to reduce the amount of data that we keep in memory.

**Comment by T-Shilov** [comment]
Hi,

Continue:

**2.5 GB**

The swap is no longer zero, as before, but 414 MB.
A little more, and there will be a collapse, as here: [https://github.com/qvarforth/trackdirect/issues/18#issue-1160735246](url)

![April 9](https://user-images.githubusercontent.com/61428202/162583488-73b1fa61-2cdb-4265-bcac-0ac1c5d6caa9.png)

**Comment by qvarforth** [comment]
Hi,
I have now improved memory handling for the frequency limit functionality, I have also added the possibility to disable the duplicate detection functionality (which uses some memory). Please try the updated code. If you still see a high memory usage, disable the frequency limit (set collector.frequency_limit to "0") and disable duplicate detection (set collector.detect_duplicates to "0").

**Comment by T-Shilov** [comment]
Thank you very much, Per!

I am testing your improvement soon, and will inform you.

**Comment by T-Shilov** [comment]
Hi,

1) **collector.py**  behavior after code update

Immediately after the start of the application:  **34.7 MB**

2) Per, let me ask you one more question: how to launch your product in a slightly different way?

For example, instead of https://example.com /
this: https://example.com/aprs/

What changes do me need to make to your products for this?


![April 20](https://user-images.githubusercontent.com/61428202/164281007-4c6aca8c-3121-433f-ab38-cd31f743a394.png)

**Comment by T-Shilov** [comment]
Hi, Per,

Unfortunately, the memory used is growing:  **1.1 GB**
But I haven't followed your recommendations yet -

> If you still see a high memory usage, disable the frequency limit 
> (set collector.frequency_limit to "0") and disable duplicate detection
> (set collector.detect_duplicates to "0").

- are they mandatory?


![April 22](https://user-images.githubusercontent.com/61428202/164760402-263b8ff0-67db-4a53-a504-7615dbcdc52d.png)

**Comment by qvarforth** [comment]
Please try to disable the frequency limit (set collector.frequency_limit to "0") and disable duplicate detection (set collector.detect_duplicates to "0"), that will affect memory usage a lot.

It should be possible to place the website at any url (including subdirectories). But if you place it in a subdirectory the "automatic" websocket url finder will not work, you need to set "websocket_url" manually in config file.

**Comment by T-Shilov** [comment]
Thanks you Per, I'll do it.
