### ISSUE TITLE
Address resolving failure of cwop.aprs.net

### ISSUE THREAD

**Issue by chjohn22** [qvarforth/trackdirect#20]
When I run docker-compose up I always get address resolving failures, it does not matter if I use APRS or CWOP.
cwop.aprs.net does resolve just fine with `dig` ran from the command line.

` INFO: Uplink Core rotate: address resolving failure of 'cwop.aprs.net' '10152': No address associated with hostname
aprsc_1
`
`
  INFO: status: setting error flag no_uplink ttl 3600
`

**Comment by pawelmuszynski** [comment]
I created aprsc Dockerfile fix for this issue. Waiting for merge.

**Comment by chjohn22** [comment]
It is merged, I will close this issue for now. Thank you very much for the pull request @pawelmuszynski !

**Comment by chjohn22** [comment]
I still get the same error. Did pull everything to get the new version but it still throws me the same error.
