### ISSUE TITLE
Metric distances shown when imperial is set after station search - Low priority

### ISSUE THREAD

**Issue by nathantcampbell** [qvarforth/trackdirect#22]
Hi,

I've found that if you have imperial units set in the option menu, but you search for a station then go straight that station's detail page, then "statistics", distances are represented in metric. However if you search for a station, click "map", then select the station then "statistics" it works as expected. It seems the station details link in the search menu needs to include the unit preference correctly.

Nathan

![1](https://user-images.githubusercontent.com/24758209/160460816-75af8725-89c1-4bf4-9639-e9639d7e59e7.JPG)
![2](https://user-images.githubusercontent.com/24758209/160460819-1971a4bb-150e-4f4e-8f9d-14dd28349bd0.JPG)
![3](https://user-images.githubusercontent.com/24758209/160460825-8ebe199e-4520-4e0a-8ecd-841e3cb73300.JPG)

**Comment by qvarforth** [comment]
Thank you for the info! It is fixed now.
