### ISSUE TITLE
Symbols of aprs objects on the map

### ISSUE THREAD

**Issue by s-s-s** [qvarforth/trackdirect#23]
I don’t understand what else needs to be done so that the symbols of aprs objects appear on the map? (
Any ideas? Any help. Thanks
http://aprs.radiocult.su/

**Comment by Vertikar** [comment]
Are you getting stations showing up in Other > Latest heard?

**Comment by s-s-s** [comment]
> Are you getting stations showing up in Other > Latest heard?

Yes, there are stations on the list

**Comment by Vertikar** [comment]
I had an issue running in docker, where I'd changed the port of the websocket service, and also the webinterface, which prevented the browser from connecting to the websocket service. 
I noticed the error in the browser console.
Have you changed those ports?

**Comment by s-s-s** [comment]
> I had an issue running in docker, where I'd changed the port of the websocket service, and also the webinterface, which prevented the browser from connecting to the websocket service. I noticed the error in the browser console. Have you changed those ports?

Thanks a lot for your feedback and ideas. A note about websocket helped me find a problem with the rules in iptables. 73 55!
