### ISSUE TITLE
filter station on gliderradar

### ISSUE THREAD

**Issue by michael067** [qvarforth/trackdirect#30]
Hi,

on gliderradar, by filtering on an object, the trace ( graph history ) disappears.
if i reset the filtering, the trace reappears with the others glider. ( i can't filter on one glider )

Thanks

**Comment by qvarforth** [comment]
The problem should have been resolved by the following commit:
https://github.com/qvarforth/trackdirect/commit/84b711a122c9b07902b167acef008ae887862180

I'm sorry for the delay.
