### ISSUE TITLE
Image missing on dockerhub?

### ISSUE THREAD

**Issue by sm3sgp** [qvarforth/trackdirect#31]
Pulling websocket (peterus/trackdirect-python:latest)...
ERROR: pull access denied for peterus/trackdirect-python, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Maybe @peterus is working on the Python3 update?

I tried to install with docker-compose two weeks ago, failed due to something, probably old docker-compose (only accepting Ver 3.3). Went back to continue the fight, but now it fails to find the peterus/trackdirect-python image on dockerhub. (https://hub.docker.com/u/peterus)

**Comment by peterus** [comment]
sorry for the long wait. I updated now the docker hub config and the python3 image is available now.

please report if you find some issues.

@qvarforth ticket can be closed.
