### ISSUE TITLE
Telemetry packets?

### ISSUE THREAD

**Issue by ha5dzs** [qvarforth/trackdirect#40]
Hi,

With your implementation, I can see my stations transmitting the equation, unit, and parameter packets, but the ones containing the actual telemetry data do not appear in the raw packets, and nothing gets displayed in the graphs.

Why is that?

Managed to replicate this with my custom DireWolf 1.6 installation, and an ESP8266-based MiniWX station as well. Both stations transmit their packets fine, and I can see them with my receiver and on aprs.fi.

If you want to check, here are the callsigns:
A68AN-10, and A68AN-13

Zoltan

**Comment by ha5dzs** [comment]
Having butchered your code, I now think this is more of an `aprslib` issue.

**Comment by shackrat** [comment]
> Having butchered your code, I now think this is more of an `aprslib` issue.

Most definitely.  I've patched aprslib which should fix telemetry for anyone having issues..  

https://github.com/shackrat/aprs-python

**Comment by ha5dzs** [comment]
Ok, I added this, will tell you how it worked in a day or so.

**Comment by ha5dzs** [comment]
Oops, it's been two weeks. Unfortunately, it didn't work. I am closing this anyway, because it is clearly not a trackdirect issue.
