### ISSUE TITLE
Trackdirect don’t work with php 8.5

### ISSUE THREAD

**Issue by michelvod** [qvarforth/trackdirect#41]
Hi!
Trackdirect don’t work with php 8.5. I can’t deploy on my server with Debian 12 Bookworm with default settings. I had to use external repository to install php 7.4 on my server, but 7.4 will be discontinued soon. Will you make improvements to support php 8.5?

**Comment by shackrat** [comment]
You only need to modify three of the .php files for PHP8 compatibility..

Modify

**Comment by qvarforth** [comment]
Thanks for the needed changes @shackrat! I have added the changes.
