### ISSUE TITLE
Run on a multiple sites/conf enabled apace2 server

### ISSUE THREAD

**Issue by leonardinux** [qvarforth/trackdirect#46]
Is possible to run trackdirect on a apache2 server with multiple  configuration enabled (We have a main site, phpmyadmin instlled on it).

TU de Leo IZ5FSA

**Comment by qvarforth** [comment]
Yes, it shouldn't be a problem (I've done that before). If you have a reverse proxy in front that handles SSL certificates, I recommend that you configure apache to run on different ports, if not, you can configure it based on domain name.
