### ISSUE TITLE
Map not showing any data. 

### ISSUE THREAD

**Issue by 9M2PJU** [qvarforth/trackdirect#47]
![image](https://github.com/user-attachments/assets/d5dda42a-61c5-4063-8003-4d2aed0600e7)
installed from docker.

WARN[0000] /home/piju/trackdirect/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 5/0
 ✔ Container trackdirect-aprsc-1      Created                                                                            0.0s
 ✔ Container trackdirect-db-1         Created                                                                            0.0s
 ✔ Container trackdirect-web-1        Created                                                                            0.0s
 ✔ Container trackdirect-collector-1  Created                                                                            0.0s
 ✔ Container trackdirect-websocket-1  Created                                                                            0.0s
Attaching to aprsc-1, collector-1, db-1, web-1, websocket-1
aprsc-1      | 2024/08/19 15:34:02.850605 aprsc[6:7f69cc196040] NOTICE: Starting up version 2.1.19-g730c5c0, instance id eiyracsm ...
aprsc-1      | 2024/08/19 15:34:02.850985 aprsc[6:7f69cc196040] INFO: After configuration FileLimit is 1048576, MaxClients is 500, xpoll using epoll
aprsc-1      | 2024/08/19 15:34:02.851314 aprsc[6:7f69cc196040] INFO: Initializing OpenSSL, built against OpenSSL 1.1.1f  31 Mar 2020 ...
db-1         |
db-1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1         |
aprsc-1      | 2024/08/19 15:34:02.860433 aprsc[6:7f69cc194700] INFO: Time thread starting: using clock_gettime
aprsc-1      | 2024/08/19 15:34:02.860485 aprsc[6:7f69cc173700] INFO: Accept thread starting...
aprsc-1      | 2024/08/19 15:34:02.860603 aprsc[6:7f69cc152700] INFO: HTTP thread starting...
aprsc-1      | 2024/08/19 15:34:02.861404 aprsc[6:7f69cc152700] INFO: Language 0 installed: fi: web/strings-fi.json
aprsc-1      | 2024/08/19 15:34:02.863583 aprsc[6:7f69cc152700] INFO: Language 1 installed: en: web/strings-en.json
aprsc-1      | 2024/08/19 15:34:02.863575 aprsc[6:7f69cc173700] INFO: Binding listening UDP socket: [::]:8080
aprsc-1      | 2024/08/19 15:34:02.863759 aprsc[6:7f69cc173700] INFO: Binding listening TCP socket: [::]:10155
aprsc-1      | 2024/08/19 15:34:02.863811 aprsc[6:7f69cc173700] INFO: Binding listening TCP socket: [::]:14580
aprsc-1      | 2024/08/19 15:34:02.863880 aprsc[6:7f69cc173700] INFO: Binding listening TCP socket: [::]:10152
aprsc-1      | 2024/08/19 15:34:02.863993 aprsc[6:7f69cc173700] INFO: Accept thread ready.
aprsc-1      | 2024/08/19 15:34:02.864023 aprsc[6:7f69cc173700] INFO: Starting 2 worker threads (configured: 2)...
aprsc-1      | 2024/08/19 15:34:02.866699 aprsc[6:7f69cc152700] INFO: Binding HTTP upload socket 0.0.0.0:8080
aprsc-1      | 2024/08/19 15:34:02.866863 aprsc[6:7f69cc152700] INFO: Binding HTTP status socket 0.0.0.0:14501
aprsc-1      | 2024/08/19 15:34:02.867044 aprsc[6:7f69cc152700] INFO: HTTP thread ready.
aprsc-1      | 2024/08/19 15:34:02.867101 aprsc[6:7f69cc0ef700] INFO: Dupecheck thread ready.
aprsc-1      | 2024/08/19 15:34:02.867117 aprsc[6:7f69cc0ce700] INFO: Uplink thread applying new configuration...
aprsc-1      | 2024/08/19 15:34:02.867191 aprsc[6:7f69cc0ce700] INFO: Uplink thread configured.
aprsc-1      | 2024/08/19 15:34:02.867201 aprsc[6:7f69cc0ce700] INFO: Uplink: 2 uplinks configured, 0 are connected, need to pick new
aprsc-1      | 2024/08/19 15:34:02.882517 aprsc[6:7f69cc0ce700] INFO: Uplink Core rotate: Connecting to euro.aprs2.net:10152 (44.5.46.14:10152) [addr 2/8]
aprsc-1      | 2024/08/19 15:34:02.934248 aprsc[6:7f69cc0ce700] INFO: Uplink Core rotate: 44.5.46.14:10152: Connection established on fd 15 using source address 172.20.0.3:39278
aprsc-1      | 2024/08/19 15:34:02.934296 aprsc[6:7f69cc0ce700] INFO: status: setting error flag no_uplink ttl 3600
db-1         | 2024-08-19 15:34:02.988 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1         | 2024-08-19 15:34:02.988 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1         | 2024-08-19 15:34:02.991 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1         | 2024-08-19 15:34:02.997 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1         | 2024-08-19 15:34:03.008 UTC [28] LOG:  database system was shut down at 2024-08-19 15:30:54 UTC
aprsc-1      | 2024/08/19 15:34:03.000693 aprsc[6:7f69cc131700] INFO: 44.5.46.14:10152: Uplink server software: # aprsc 2.1.19-g730c5c0
aprsc-1      | 2024/08/19 15:34:03.000762 aprsc[6:7f69cc131700] INFO: 44.5.46.14:10152: Connected to server, logging in
db-1         | 2024-08-19 15:34:03.032 UTC [1] LOG:  database system is ready to accept connections
aprsc-1      | 2024/08/19 15:34:03.052062 aprsc[6:7f69cc131700] INFO: 44.5.46.14:10152: Uplink server login response: # logresp 9M2PJU-0 verified, server T2SWEDEN
aprsc-1      | 2024/08/19 15:34:03.052090 aprsc[6:7f69cc131700] INFO: 44.5.46.14:10152: Uplink logged in to server T2SWEDEN
web-1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.4. Set the 'ServerName' directive globally to suppress this message
web-1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.4. Set the 'ServerName' directive globally to suppress this message
web-1        | [Mon Aug 19 15:34:04.181212 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.2.34 configured -- resuming normal operations
web-1        | [Mon Aug 19 15:34:04.183529 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
collector-1  | 2024-08-19 15:34:04,462 - trackdirect - WARNING - Starting (Collecting from aprsc:10152 using 9M2PJU and 12970)
collector-1  | 2024-08-19 15:34:04,494 - aprslib.IS - INFO - Attempting connection to aprsc:10152
collector-1  | 2024-08-19 15:34:04,500 - aprslib.IS - INFO - Connected to ('172.20.0.3', 10152)
collector-1  | 2024-08-19 15:34:04,522 - aprslib.IS - INFO - Sending login information
collector-1  | 2024-08-19 15:34:04,522 - aprslib.IS - INFO - Login successful
websocket-1  | 2024-08-19 15:34:04,564 - trackdirect - WARNING - Starting master with PID 12 (on CPU id(s): 0)
aprsc-1      | 2024/08/19 15:34:06.963304 aprsc[6:7f69cc0ce700] INFO: status: clearing error flag no_uplink

**Comment by ha5dzs** [comment]
I am not using it from Docker, but I had this happen to me when I try to access the server using https. The objects are overlaid on the map using JavaScript, and the data is obtained from the collector using WebSocket. In the debug console on the browser, you should be some error messages.

Hope this helps!

**Comment by 9M2PJU** [comment]
> I am not using it from Docker, but I had this happen to me when I try to access the server using https. The objects are overlaid on the map using JavaScript, and the data is obtained from the collector using WebSocket. In the debug console on the browser, you should be some error messages.
> 
> Hope this helps!

Thanks for reply. I have found the problem and fix it.
