### ISSUE TITLE
wrong path setting in index.php for bootstrap

### ISSUE THREAD

**Issue by peterus** [qvarforth/trackdirect#5]
https://github.com/qvarforth/trackdirect/commit/1f10ea0f9443a1aa2d5402b37cfbcb8af3f584f6#r66129347

**Comment by US1GHQ** [comment]
All working, if enable Rewrite Engine, and set Apache directory to /home/USER/trackdirect/htdocs not to /home/USER/trackdirect/htdocs/public

**Comment by peterus** [comment]
@US1GHQ can you diff your config to the one which is in the repo? thanks!

config/000-default.conf

**Comment by qvarforth** [comment]
I modified the include path to be relative instead, the should support both configuration alternatives.

**Comment by peterus** [comment]
thanks for the update!
