### ISSUE TITLE
Docker Config Is Not Valid for Ubuntu 20.04

### ISSUE THREAD

**Issue by W4JEW** [qvarforth/trackdirect#7]
I keep running into dead-ends with each iteration of trying to install the code in this repository.

The documentation starts by saying that it's for Ubuntu 20.04 and that's exactly what I am running.

I've tried with both the version of Docker (docker.io) included in the Ubuntu repository as well as installing Docker from the official Docker repository (docker-ce), along with containerd, and docker-compose. Neither of them work with the docker-compose.yml file that is included.

Any time I run docker-compose, I get the following error:

```ERROR: Version in "./docker-compose-rel.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/```

**Comment by W4JEW** [comment]
It looks like there's a pull request that resolves some of the issues that I'm running into. Would you be able to review the pull request and merge the changes into main?

**Comment by qvarforth** [comment]
Yes! I will merge that (I have discussed that pr with peterus, the plan was to merge it today).
