### ISSUE TITLE
Installation Process Works Nicely - Until Setup OGN Device Data

### ISSUE THREAD

**Issue by W4JEW** [qvarforth/trackdirect#8]
I've tried to work through the installation routine up through the section on setting up the OGN data.

It's very difficult to tell which user the script is supposed to be run as. There are Postgres authentication errors if you try to run the script as the regular user account you're logged into Ubuntu with. I've also tried creating a user account for "trackdirect", then using su to login as that user and run the ogn data script and get a similar error - the username specified is the same as the original account I was logged in as.

Then, when I move on to trying to start the collector, I get the following error:

```trackdirect@aprsdirect:~$ ~/trackdirect/server/scripts/collector.sh trackdirect.ini 0
/home/trackdirect/.local/lib/python2.7/site-packages/autobahn/wamp/auth.py:43: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
2022-02-12 14:58:18,991 - trackdirect - WARNING - Starting (Collecting from 127.0.0.1:10152 using CALLSIGN and PASSCODE)
2022-02-12 14:58:18,993 - trackdirect - ERROR - FATAL:  password authentication failed for user "USER"
Traceback (most recent call last):
  File "./bin/collector.py", line 59, in <module>
    saveOgnStationsWithMissingIdentity)
  File "/home/trackdirect/trackdirect/server/trackdirect/TrackDirectDataCollector.py", line 52, in __init__
    self.db = dbConnection.getConnection(True)
  File "/home/trackdirect/trackdirect/server/trackdirect/database/DatabaseConnection.py", line 44, in getConnection
    DatabaseConnection.db = self._createNewConnection()
  File "/home/trackdirect/trackdirect/server/trackdirect/database/DatabaseConnection.py", line 66, in _createNewConnection
    cursor_factory=psycopg2.extras.DictCursor)
  File "/home/trackdirect/.local/lib/python2.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  password authentication failed for user "USER"```

Did anyone actually go through the set up routine and follow these instructions step-by-step? I've repeated the steps several times, each time rolling back the Ubuntu Server 20.04 VM I'm trying to the installation on back to a freshly installed image. I consistently run into the same issues.

**Comment by qvarforth** [comment]
Yes, the instructions was tested as soon as a couple of weeks ago. But please note that the instructions is not intended to be something that you can follow exactly without any adaptions. The instructions is written for experienced developers that want to set up a development enviroment.

In general all tools should be executed as a regular user (not root).

The error that you have here is related to database login. When creating the database you are supposed to replace "{USER}" with your linux username.
