### ISSUE TITLE
"Use imperial units" is negated

### ISSUE THREAD

**Issue by peterus** [qvarforth/trackdirect#9]
The "Use imperial units" checkbox is the other way around. When checked the numbers are not in imperial (m, km, km/h, ...), when not checked the numbers are in imperial (miles, ...).

**Comment by qvarforth** [comment]
I have seen this problem as well. But it is not always like this, it is a little bit more complicated than it is the opposite. I will take a look on the problem.

**Comment by qvarforth** [comment]
Should be fixed now. Closing issue.
